//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Optimizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Optimizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CLASSES_ROOT\DesktopBackground\Shell\DesktopShortcuts]
        ///&quot;MUIVerb&quot;=&quot;Desktop Shortcuts&quot;
        ///&quot;SubCommands&quot;=&quot;theme;wallpaper;scrnsavr;desktopicons;sound;cursor;DPI;color&quot;
        ///&quot;icon&quot;=&quot;desk.cpl&quot;
        ///&quot;Position&quot;=-
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\theme]
        ///@=&quot;Change Theme&quot;
        ///&quot;icon&quot;=&quot;imageres.dll,145&quot;
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\theme\command]
        ///@=&quot;control desk [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DesktopShortcuts {
            get {
                return ResourceManager.GetString("DesktopShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\Software\Policies\microsoft\office\16.0\osm\preventedapplications]
        ///&quot;accesssolution&quot;=dword:00000001
        ///&quot;olksolution&quot;=dword:00000001
        ///&quot;onenotesolution&quot;=dword:00000001
        ///&quot;pptsolution&quot;=dword:00000001
        ///&quot;projectsolution&quot;=dword:00000001
        ///&quot;publishersolution&quot;=dword:00000001
        ///&quot;visiosolution&quot;=dword:00000001
        ///&quot;wdsolution&quot;=dword:00000001
        ///&quot;xlsolution&quot;=dword:00000001
        /// 
        ///[HKEY_CURRENT_USER\Software\Policies\microsoft\office\16.0\osm\preventedsolutiontypes]
        ///&quot;agave&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DisableOfficeTelemetry {
            get {
                return ResourceManager.GetString("DisableOfficeTelemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schtasks /end /tn &quot;\Microsoft\Office\OfficeTelemetryAgentFallBack2016&quot;
        ///schtasks /change /tn &quot;\Microsoft\Office\OfficeTelemetryAgentFallBack2016&quot; /disable
        ///schtasks /end /tn &quot;\Microsoft\Office\OfficeTelemetryAgentLogOn2016&quot;
        ///schtasks /change /tn &quot;\Microsoft\Office\OfficeTelemetryAgentLogOn2016&quot; /disable
        ///.
        /// </summary>
        internal static string DisableOfficeTelemetryTasks {
            get {
                return ResourceManager.GetString("DisableOfficeTelemetryTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schtasks /end /tn &quot;\Microsoft\Windows\Customer Experience Improvement Program\Consolidator&quot;
        ///schtasks /change /tn &quot;\Microsoft\Windows\Customer Experience Improvement Program\Consolidator&quot; /disable
        ///schtasks /end /tn &quot;\Microsoft\Windows\Customer Experience Improvement Program\BthSQM&quot;
        ///schtasks /change /tn &quot;\Microsoft\Windows\Customer Experience Improvement Program\BthSQM&quot; /disable
        ///schtasks /end /tn &quot;\Microsoft\Windows\Customer Experience Improvement Program\KernelCeipTask&quot;
        ///schtasks /change /tn &quot;\Microsoft\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DisableTelemetryTasks {
            get {
                return ResourceManager.GetString("DisableTelemetryTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schtasks /end /tn &quot;\Microsoft\XblGameSave\XblGameSaveTask&quot;
        ///schtasks /change /tn &quot;\Microsoft\XblGameSave\XblGameSaveTask&quot; /disable
        ///schtasks /end /tn &quot;\Microsoft\XblGameSave\XblGameSaveTaskLogon&quot;
        ///schtasks /change /tn &quot;\Microsoft\XblGameSave\XblGameSaveTaskLogon&quot; /disable
        ///.
        /// </summary>
        internal static string DisableXboxTasks {
            get {
                return ResourceManager.GetString("DisableXboxTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;restartButton&quot;: &quot;Εφαρμογή &amp; Επανεκκίνηση&quot;,
        ///	&quot;restartButton8&quot;: &quot;Εφαρμογή &amp; Επανεκκίνηση&quot;,
        ///	&quot;restartButton10&quot;: &quot;Εφαρμογή &amp; Επανεκκίνηση&quot;,
        ///	&quot;restartAndApply&quot;: &quot;Επανεκκίνηση για την εφαρμογή των αλλαγών;&quot;,
        ///	&quot;txtVersion&quot;: &quot;Έκδοση: {VN}&quot;,
        ///	&quot;txtBitness&quot;: &quot;Αρχιτεκτονική {BITS}&quot;,
        ///	&quot;linkUpdate&quot;: &quot;Διαθέσιμη ενημέρωση&quot;,
        ///	&quot;lblLab&quot;: &quot;Πειραματική έκδοση&quot;,
        ///	&quot;performanceSw&quot;: &quot;Βελτιστοποίηση Απόδοσης Συστήματος&quot;,
        ///	&quot;networkSw&quot;: &quot;Βελτιστοποίηση Δικτύου&quot;,
        ///	&quot;defenderSw&quot;: &quot;Απενεργοποίηση Windows Defender&quot;,
        ///	&quot;syste [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EL {
            get {
                return ResourceManager.GetString("EL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;restartButton&quot;: &quot;Apply &amp; Restart&quot;,
        ///	&quot;restartButton8&quot;: &quot;Apply &amp; Restart&quot;,
        ///	&quot;restartButton10&quot;: &quot;Apply &amp; Restart&quot;,
        ///	&quot;restartAndApply&quot;: &quot;restart to apply changes?&quot;,
        ///	&quot;txtVersion&quot;: &quot;Version: {VN}&quot;,
        ///	&quot;txtBitness&quot;: &quot;You are working with {BITS}&quot;,
        ///	&quot;linkUpdate&quot;: &quot;Update available&quot;,
        ///	&quot;lblLab&quot;: &quot;Experimental build\n(delete after testing)&quot;,
        ///	&quot;performanceSw&quot;: &quot;Enable Performance Tweaks&quot;,
        ///	&quot;networkSw&quot;: &quot;Disable Network Throttling&quot;,
        ///	&quot;defenderSw&quot;: &quot;Disable Windows Defender&quot;,
        ///	&quot;systemRestoreSw&quot;: &quot;Disable Sy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EN {
            get {
                return ResourceManager.GetString("EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\Software\Policies\microsoft\office\16.0\osm\preventedapplications]
        ///&quot;accesssolution&quot;=-
        ///&quot;olksolution&quot;=-
        ///&quot;onenotesolution&quot;=-
        ///&quot;pptsolution&quot;=-
        ///&quot;projectsolution&quot;=-
        ///&quot;publishersolution&quot;=-
        ///&quot;visiosolution&quot;=-
        ///&quot;wdsolution&quot;=-
        ///&quot;xlsolution&quot;=-
        /// 
        ///[HKEY_CURRENT_USER\Software\Policies\microsoft\office\16.0\osm\preventedsolutiontypes]
        ///&quot;agave&quot;=-
        ///&quot;appaddins&quot;=-
        ///&quot;comaddins&quot;=-
        ///&quot;documentfiles&quot;=-
        ///&quot;templatefiles&quot;=-
        ///.
        /// </summary>
        internal static string EnableOfficeTelemetry {
            get {
                return ResourceManager.GetString("EnableOfficeTelemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schtasks /change /tn &quot;\Microsoft\Office\OfficeTelemetryAgentFallBack2016&quot; /enable
        ///schtasks /change /tn &quot;\Microsoft\Office\OfficeTelemetryAgentLogOn2016&quot; /enable
        ///.
        /// </summary>
        internal static string EnableOfficeTelemetryTasks {
            get {
                return ResourceManager.GetString("EnableOfficeTelemetryTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schtasks /change /tn &quot;\Microsoft\Windows\Customer Experience Improvement Program\Consolidator&quot; /enable
        ///schtasks /change /tn &quot;\Microsoft\Windows\Customer Experience Improvement Program\BthSQM&quot; /enable
        ///schtasks /change /tn &quot;\Microsoft\Windows\Customer Experience Improvement Program\KernelCeipTask&quot; /enable
        ///schtasks /change /tn &quot;\Microsoft\Windows\Customer Experience Improvement Program\UsbCeip&quot; /enable
        ///schtasks /change /tn &quot;\Microsoft\Windows\Customer Experience Improvement Program\Uploader&quot; /enable
        ///schta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EnableTelemetryTasks {
            get {
                return ResourceManager.GetString("EnableTelemetryTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schtasks /change /tn &quot;\Microsoft\XblGameSave\XblGameSaveTask&quot; /enable
        ///schtasks /change /tn &quot;\Microsoft\XblGameSave\XblGameSaveTaskLogon&quot; /enable
        ///.
        /// </summary>
        internal static string EnableXboxTasks {
            get {
                return ResourceManager.GetString("EnableXboxTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] hosts {
            get {
                object obj = ResourceManager.GetObject("hosts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CLASSES_ROOT\*\shell\runas]
        ///@=&quot;Take Ownership&quot;
        ///&quot;NoWorkingDirectory&quot;=&quot;&quot;
        ///
        ///[HKEY_CLASSES_ROOT\*\shell\runas\command]
        ///@=&quot;cmd.exe /c takeown /f \&quot;%1\&quot; &amp;&amp; icacls \&quot;%1\&quot; /grant administrators:F&quot;
        ///&quot;IsolatedCommand&quot;=&quot;cmd.exe /c takeown /f \&quot;%1\&quot; &amp;&amp; icacls \&quot;%1\&quot; /grant administrators:F&quot;
        ///
        ///[HKEY_CLASSES_ROOT\Directory\shell\runas]
        ///@=&quot;Take Ownership&quot;
        ///&quot;NoWorkingDirectory&quot;=&quot;&quot;
        ///
        ///[HKEY_CLASSES_ROOT\Directory\shell\runas\command]
        ///@=&quot;cmd.exe /c takeown /f \&quot;%1\&quot; /r /d  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InstallTakeOwnership {
            get {
                return ResourceManager.GetString("InstallTakeOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OneDrive_Uninstaller {
            get {
                object obj = ResourceManager.GetObject("OneDrive_Uninstaller", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CLASSES_ROOT\DesktopBackground\Shell\Power Menu]
        ///&quot;MUIVerb&quot;=&quot;Power Menu&quot;
        ///&quot;SubCommands&quot;=&quot;lock;logoff;switch;sleep;hibernate;restart;safemode;shutdown;hybridshutdown&quot;
        ///&quot;Icon&quot;=&quot;shell32.dll,215&quot;
        ///&quot;Position&quot;=&quot;bottom&quot;
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\lock]
        ///@=&quot;Lock&quot;
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\lock\command]
        ///@=&quot;Rundll32 User32.dll,LockWorkStati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PowerMenu {
            get {
                return ResourceManager.GetString("PowerMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///
        ///[-HKEY_CLASSES_ROOT\*\shell\runas]
        ///
        ///[-HKEY_CLASSES_ROOT\Directory\shell\runas]
        ///.
        /// </summary>
        internal static string RemoveTakeOwnership {
            get {
                return ResourceManager.GetString("RemoveTakeOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;restartButton&quot;: &quot;Применить и перезапустить&quot;,
        ///	&quot;restartButton8&quot;: &quot;Применить и перезапустить&quot;,
        ///	&quot;restartButton10&quot;: &quot;Применить и перезапустить&quot;,
        ///	&quot;restartAndApply&quot;: &quot;перезагрузить, чтобы изменения вступили в силу?&quot;,
        ///	&quot;txtVersion&quot;: &quot;Версия: {VN}&quot;,
        ///	&quot;txtBitness&quot;: &quot;Вы работаете с {BITS}&quot;,
        ///	&quot;linkUpdate&quot;: &quot;обновление доступно&quot;,
        ///	&quot;lblLab&quot;: &quot;экспериментальная сборка\n(удалить после тестирования)&quot;,
        ///	&quot;performanceSw&quot;: &quot;Вкл Настройки производительности&quot;,
        ///	&quot;networkSw&quot;: &quot;Отключить Сетевое регулирование&quot;,
        ///	&quot;d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RU {
            get {
                return ResourceManager.GetString("RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CLASSES_ROOT\DesktopBackground\Shell\SystemShortcuts]
        ///&quot;MUIVerb&quot;=&quot;System Shortcuts&quot;
        ///&quot;SubCommands&quot;=&quot;admintools;datetime;regional;folderoptions;gmode;internetoptions;network;power;appwiz;rbin;run;search;services;sysdm;user;user2;flip3d&quot;
        ///&quot;icon&quot;=&quot;sysdm.cpl&quot;
        ///&quot;Position&quot;=-
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\admintools]
        ///@=&quot;Administrative Tools&quot;
        ///&quot;icon&quot;=&quot;imageres.dll,109&quot;
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Micros [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SystemShortcuts {
            get {
                return ResourceManager.GetString("SystemShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CLASSES_ROOT\DesktopBackground\Shell\SystemTools]
        ///&quot;MUIVerb&quot;=&quot;System Tools&quot;
        ///&quot;SubCommands&quot;=&quot;control;cleanmgr;devmgr;event;regedit;secctr;msconfig;taskmgr;taskschd;wu&quot;
        ///&quot;icon&quot;=&quot;imageres.dll,104&quot;
        ///&quot;Position&quot;=-
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\control]
        ///@=&quot;Control Panel&quot;
        ///&quot;icon&quot;=&quot;control.exe&quot;
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\control\command]
        ///@=&quot;c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SystemTools {
            get {
                return ResourceManager.GetString("SystemTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CLASSES_ROOT\DesktopBackground\Shell\WindowsApps]
        ///&quot;MUIVerb&quot;=&quot;Windows Apps&quot;
        ///&quot;SubCommands&quot;=&quot;calc;chmap;cmd;dfrg;ie;notepad;paint;psr;snip;srd;srt;tsch;wmp;wordpad&quot;
        ///&quot;icon&quot;=&quot;imageres.dll,152&quot;
        ///&quot;Position&quot;=-
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\calc]
        ///@=&quot;Calculator&quot;
        ///&quot;icon&quot;=&quot;calc.exe&quot;
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\calc\command]
        ///@=&quot;calc.exe&quot;
        ///
        ///[HK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WindowsApps {
            get {
                return ResourceManager.GetString("WindowsApps", resourceCulture);
            }
        }
    }
}
