//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Optimizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Optimizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CLASSES_ROOT\Directory\shell\OpenWithCMD]
        ///@=&quot;Open Command Prompt here&quot;
        ///&quot;Icon&quot;=&quot;cmd.exe&quot;
        ///&quot;NoWorkingDirectory&quot;=&quot;&quot;
        ///
        ///[HKEY_CLASSES_ROOT\Directory\shell\OpenWithCMD\command]
        ///@=&quot;cmd.exe /s /k pushd \&quot;%V\&quot;&quot;
        ///
        ///[HKEY_CLASSES_ROOT\Directory\Background\shell\OpenWithCMD]
        ///@=&quot;Open Command Prompt here&quot;
        ///&quot;Icon&quot;=&quot;cmd.exe&quot;
        ///&quot;NoWorkingDirectory&quot;=&quot;&quot;
        ///
        ///[HKEY_CLASSES_ROOT\Directory\Background\shell\OpenWithCMD\command]
        ///@=&quot;cmd.exe /s /k pushd \&quot;%V\&quot;&quot;
        ///
        ///[HKEY_CLASSES_ROOT\Drive\shell\OpenWit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddOpenWithCMD {
            get {
                return ResourceManager.GetString("AddOpenWithCMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap brazil {
            get {
                object obj = ResourceManager.GetObject("brazil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap china {
            get {
                object obj = ResourceManager.GetObject("china", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;btnAbout&quot;: &quot;确定&quot;,
        ///	&quot;restartButton&quot;: &quot;现在重启&quot;,
        ///	&quot;restartButton8&quot;: &quot;现在重启&quot;,
        ///	&quot;restartButton10&quot;: &quot;现在重启&quot;,
        ///	&quot;restartAndApply&quot;: &quot;重新启动以应用更改?&quot;,
        ///	&quot;txtVersion&quot;: &quot;版本: {VN}&quot;,
        ///	&quot;txtBitness&quot;: &quot;您使用的是{BITS}&quot;,
        ///	&quot;linkUpdate&quot;: &quot;更新可用&quot;,
        ///	&quot;lblLab&quot;: &quot;实验构建\n(删除后测试)&quot;,
        ///	&quot;performanceSw&quot;: &quot;启用性能调整&quot;,
        ///	&quot;networkSw&quot;: &quot;禁用网络节流&quot;,
        ///	&quot;defenderSw&quot;: &quot;禁用 Windows Defender&quot;,
        ///	&quot;systemRestoreSw&quot;: &quot;禁用 System Restore&quot;,
        ///	&quot;printSw&quot;: &quot;禁用打印服务&quot;,
        ///	&quot;mediaSharingSw&quot;: &quot;禁用媒体播放器共享&quot;,
        ///	&quot;faxSw&quot;: &quot;禁用传真服务&quot;,
        ///	&quot;reportingSw&quot;: &quot;禁用错误报告&quot;,
        ///	&quot;homegroupSw&quot;: &quot;禁用 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CN {
            get {
                return ResourceManager.GetString("CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;btnAbout&quot;: &quot;OK&quot;,
        ///	&quot;restartButton&quot;: &quot;Restartovat nyní&quot;,
        ///	&quot;restartButton8&quot;: &quot;Restartovat nyní&quot;,
        ///	&quot;restartButton10&quot;: &quot;Restartovat nyní&quot;,
        ///	&quot;restartAndApply&quot;: &quot;Restartovat a použít změny?&quot;,
        ///	&quot;txtVersion&quot;: &quot;Verze: {VN}&quot;,
        ///	&quot;txtBitness&quot;: &quot;Pracujete s {BITS}ovou verzí&quot;,
        ///	&quot;linkUpdate&quot;: &quot;Dostupná aktualizace&quot;,
        ///	&quot;lblLab&quot;: &quot;Experimentální sestavení\n(po testování smazat)&quot;,
        ///	&quot;performanceSw&quot;: &quot;Povolit Vylepšení výkonu&quot;,
        ///	&quot;networkSw&quot;: &quot;Zakázat Omezení sítě&quot;,
        ///	&quot;defenderSw&quot;: &quot;Zakázat Windows Defender&quot;,
        ///	&quot;sys [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CZ {
            get {
                return ResourceManager.GetString("CZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap czech {
            get {
                object obj = ResourceManager.GetObject("czech", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;btnAbout&quot;: &quot;OK&quot;,
        ///	&quot;restartButton&quot;: &quot;Jetzt neu starten&quot;,
        ///	&quot;restartButton8&quot;: &quot;Jetzt neu starten&quot;,
        ///	&quot;restartButton10&quot;: &quot;Jetzt neu starten&quot;,
        ///	&quot;restartAndApply&quot;: &quot;Neu starten, um Änderungen anzuwenden?&quot;,
        ///	&quot;txtVersion&quot;: &quot;Version: {VN}&quot;,
        ///	&quot;txtBitness&quot;: &quot;Betriebssystem: {BITS}&quot;,
        ///	&quot;linkUpdate&quot;: &quot;Update verfügbar&quot;,
        ///	&quot;lblLab&quot;: &quot;Experimenteller Build\n(nach dem Testen löschen)&quot;,
        ///	&quot;performanceSw&quot;: &quot;Leistungsoptimierung aktivieren&quot;,
        ///	&quot;networkSw&quot;: &quot;Netzwerkdrosselung deaktivieren&quot;,
        ///	&quot;defenderSw&quot;: &quot;Windows  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DE {
            get {
                return ResourceManager.GetString("DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CLASSES_ROOT\DesktopBackground\Shell\DesktopShortcuts]
        ///&quot;MUIVerb&quot;=&quot;Desktop Shortcuts&quot;
        ///&quot;SubCommands&quot;=&quot;theme;wallpaper;scrnsavr;desktopicons;sound;cursor;DPI;color&quot;
        ///&quot;icon&quot;=&quot;desk.cpl&quot;
        ///&quot;Position&quot;=-
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\theme]
        ///@=&quot;Change Theme&quot;
        ///&quot;icon&quot;=&quot;imageres.dll,145&quot;
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\theme\command]
        ///@=&quot;control desk [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DesktopShortcuts {
            get {
                return ResourceManager.GetString("DesktopShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rem USE AT OWN RISK AS IS WITHOUT WARRANTY OF ANY KIND !!!!!
        ///
        ///rem https://docs.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/security-malware-windows-defender-disableantispyware
        ///rem &quot;DisableAntiSpyware&quot; is discontinued and will be ignored on client devices, as of the August 2020 (version 4.18.2007.8) update to Microsoft Defender Antivirus.
        ///
        ///rem Disable Tamper Protection First !!!!!
        ///rem https://www.tenforums.com/tutorials/123792-turn-off-tamper-protection-windows-defender-antivirus.html
        ///reg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DisableDefenderSafeMode1903Plus {
            get {
                return ResourceManager.GetString("DisableDefenderSafeMode1903Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\Software\Policies\microsoft\office\16.0\osm\preventedapplications]
        ///&quot;accesssolution&quot;=dword:00000001
        ///&quot;olksolution&quot;=dword:00000001
        ///&quot;onenotesolution&quot;=dword:00000001
        ///&quot;pptsolution&quot;=dword:00000001
        ///&quot;projectsolution&quot;=dword:00000001
        ///&quot;publishersolution&quot;=dword:00000001
        ///&quot;visiosolution&quot;=dword:00000001
        ///&quot;wdsolution&quot;=dword:00000001
        ///&quot;xlsolution&quot;=dword:00000001
        /// 
        ///[HKEY_CURRENT_USER\Software\Policies\microsoft\office\16.0\osm\preventedsolutiontypes]
        ///&quot;agave&quot;=dword:0000000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DisableOfficeTelemetry {
            get {
                return ResourceManager.GetString("DisableOfficeTelemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schtasks /end /tn &quot;\Microsoft\Office\OfficeTelemetryAgentFallBack2016&quot;
        ///schtasks /change /tn &quot;\Microsoft\Office\OfficeTelemetryAgentFallBack2016&quot; /disable
        ///schtasks /end /tn &quot;\Microsoft\Office\OfficeTelemetryAgentLogOn2016&quot;
        ///schtasks /change /tn &quot;\Microsoft\Office\OfficeTelemetryAgentLogOn2016&quot; /disable
        ///
        ///schtasks /end /tn &quot;\Microsoft\Office\OfficeTelemetryAgentFallBack&quot;
        ///schtasks /change /tn &quot;\Microsoft\Office\OfficeTelemetryAgentFallBack&quot; /disable
        ///schtasks /end /tn &quot;\Microsoft\Office\OfficeTelemetryAgentLogOn&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DisableOfficeTelemetryTasks {
            get {
                return ResourceManager.GetString("DisableOfficeTelemetryTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schtasks /end /tn &quot;\Microsoft\Windows\Customer Experience Improvement Program\Consolidator&quot;
        ///schtasks /change /tn &quot;\Microsoft\Windows\Customer Experience Improvement Program\Consolidator&quot; /disable
        ///schtasks /end /tn &quot;\Microsoft\Windows\Customer Experience Improvement Program\BthSQM&quot;
        ///schtasks /change /tn &quot;\Microsoft\Windows\Customer Experience Improvement Program\BthSQM&quot; /disable
        ///schtasks /end /tn &quot;\Microsoft\Windows\Customer Experience Improvement Program\KernelCeipTask&quot;
        ///schtasks /change /tn &quot;\Microsoft\Windo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DisableTelemetryTasks {
            get {
                return ResourceManager.GetString("DisableTelemetryTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schtasks /end /tn &quot;\Microsoft\XblGameSave\XblGameSaveTask&quot;
        ///schtasks /change /tn &quot;\Microsoft\XblGameSave\XblGameSaveTask&quot; /disable
        ///schtasks /end /tn &quot;\Microsoft\XblGameSave\XblGameSaveTaskLogon&quot;
        ///schtasks /change /tn &quot;\Microsoft\XblGameSave\XblGameSaveTaskLogon&quot; /disable
        ///.
        /// </summary>
        internal static string DisableXboxTasks {
            get {
                return ResourceManager.GetString("DisableXboxTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;btnAbout&quot;: &quot;Εντάξει&quot;,
        ///	&quot;restartButton&quot;: &quot;Επανεκκίνηση τώρα&quot;,
        ///	&quot;restartButton8&quot;: &quot;Επανεκκίνηση τώρα&quot;,
        ///	&quot;restartButton10&quot;: &quot;Επανεκκίνηση τώρα&quot;,
        ///	&quot;restartAndApply&quot;: &quot;Επανεκκίνηση για την εφαρμογή των αλλαγών;&quot;,
        ///	&quot;txtVersion&quot;: &quot;Έκδοση: {VN}&quot;,
        ///	&quot;txtBitness&quot;: &quot;Αρχιτεκτονική {BITS}&quot;,
        ///	&quot;linkUpdate&quot;: &quot;Διαθέσιμη ενημέρωση&quot;,
        ///	&quot;lblLab&quot;: &quot;Πειραματική έκδοση&quot;,
        ///	&quot;performanceSw&quot;: &quot;Βελτιστοποίηση Απόδοσης Συστήματος&quot;,
        ///	&quot;networkSw&quot;: &quot;Βελτιστοποίηση Δικτύου&quot;,
        ///	&quot;defenderSw&quot;: &quot;Απενεργοποίηση Windows Defender&quot;,
        ///	&quot;systemResto [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EL {
            get {
                return ResourceManager.GetString("EL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;btnAbout&quot;: &quot;OK&quot;,
        ///	&quot;restartButton&quot;: &quot;Restart now&quot;,
        ///	&quot;restartButton8&quot;: &quot;Restart now&quot;,
        ///	&quot;restartButton10&quot;: &quot;Restart now&quot;,
        ///	&quot;restartAndApply&quot;: &quot;Restart to apply changes?&quot;,
        ///	&quot;txtVersion&quot;: &quot;Version: {VN}&quot;,
        ///	&quot;txtBitness&quot;: &quot;You are working with {BITS}&quot;,
        ///	&quot;linkUpdate&quot;: &quot;Update available&quot;,
        ///	&quot;lblLab&quot;: &quot;Experimental build\n(delete after testing)&quot;,
        ///	&quot;performanceSw&quot;: &quot;Enable Performance Tweaks&quot;,
        ///	&quot;networkSw&quot;: &quot;Disable Network Throttling&quot;,
        ///	&quot;defenderSw&quot;: &quot;Disable Windows Defender&quot;,
        ///	&quot;systemRestoreSw&quot;: &quot;Disable System  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EN {
            get {
                return ResourceManager.GetString("EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\Software\Policies\microsoft\office\16.0\osm\preventedapplications]
        ///&quot;accesssolution&quot;=-
        ///&quot;olksolution&quot;=-
        ///&quot;onenotesolution&quot;=-
        ///&quot;pptsolution&quot;=-
        ///&quot;projectsolution&quot;=-
        ///&quot;publishersolution&quot;=-
        ///&quot;visiosolution&quot;=-
        ///&quot;wdsolution&quot;=-
        ///&quot;xlsolution&quot;=-
        /// 
        ///[HKEY_CURRENT_USER\Software\Policies\microsoft\office\16.0\osm\preventedsolutiontypes]
        ///&quot;agave&quot;=-
        ///&quot;appaddins&quot;=-
        ///&quot;comaddins&quot;=-
        ///&quot;documentfiles&quot;=-
        ///&quot;templatefiles&quot;=-
        ///.
        /// </summary>
        internal static string EnableOfficeTelemetry {
            get {
                return ResourceManager.GetString("EnableOfficeTelemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schtasks /change /tn &quot;\Microsoft\Office\OfficeTelemetryAgentFallBack2016&quot; /enable
        ///schtasks /change /tn &quot;\Microsoft\Office\OfficeTelemetryAgentLogOn2016&quot; /enable
        ///
        ///schtasks /change /tn &quot;\Microsoft\Office\OfficeTelemetryAgentFallBack&quot; /enable
        ///schtasks /change /tn &quot;\Microsoft\Office\OfficeTelemetryAgentLogOn&quot; /enable
        ///
        ///reg add &quot;HKCU\SOFTWARE\Microsoft\Office\15.0\Outlook\Options\Mail&quot; /v &quot;EnableLogging&quot; /t REG_DWORD /d 1 /f
        ///reg add &quot;HKCU\SOFTWARE\Microsoft\Office\16.0\Outlook\Options\Mail&quot; /v &quot;EnableLogging&quot; /t  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EnableOfficeTelemetryTasks {
            get {
                return ResourceManager.GetString("EnableOfficeTelemetryTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schtasks /change /tn &quot;\Microsoft\Windows\Customer Experience Improvement Program\Consolidator&quot; /enable
        ///schtasks /change /tn &quot;\Microsoft\Windows\Customer Experience Improvement Program\BthSQM&quot; /enable
        ///schtasks /change /tn &quot;\Microsoft\Windows\Customer Experience Improvement Program\KernelCeipTask&quot; /enable
        ///schtasks /change /tn &quot;\Microsoft\Windows\Customer Experience Improvement Program\UsbCeip&quot; /enable
        ///schtasks /change /tn &quot;\Microsoft\Windows\Customer Experience Improvement Program\Uploader&quot; /enable
        ///schtasks / [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EnableTelemetryTasks {
            get {
                return ResourceManager.GetString("EnableTelemetryTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schtasks /change /tn &quot;\Microsoft\XblGameSave\XblGameSaveTask&quot; /enable
        ///schtasks /change /tn &quot;\Microsoft\XblGameSave\XblGameSaveTaskLogon&quot; /enable
        ///.
        /// </summary>
        internal static string EnableXboxTasks {
            get {
                return ResourceManager.GetString("EnableXboxTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;btnAbout&quot;: &quot;OK&quot;,
        ///	&quot;restartButton&quot;: &quot;reiniciar ahora&quot;,
        ///	&quot;restartButton8&quot;: &quot;reiniciar ahora&quot;,
        ///	&quot;restartButton10&quot;: &quot;reiniciar ahora&quot;,
        ///	&quot;restartAndApply&quot;: &quot;Reiniciar para aplicar cambios?&quot;,
        ///	&quot;txtVersion&quot;: &quot;Versión: {VN}&quot;,
        ///	&quot;txtBitness&quot;: &quot;Estas trabajando con {BITS}&quot;,
        ///	&quot;linkUpdate&quot;: &quot;Actualización disponible&quot;,
        ///	&quot;lblLab&quot;: &quot;Lamzamiento experimental\n(eliminar después de la prueba)&quot;,
        ///	&quot;CleanPreviewForm&quot;: &quot;Vista Previa Limpia&quot;,
        ///	&quot;performanceSw&quot;: &quot;Habilitar ajustes de rendimiento&quot;,
        ///	&quot;networkSw&quot;: &quot;Deshabilitar la  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ES {
            get {
                return ResourceManager.GetString("ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ipconfig /flushdns
        ///ipconfig /registerdns.
        /// </summary>
        internal static string FlushDNSCache {
            get {
                return ResourceManager.GetString("FlushDNSCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;btnAbout&quot;: &quot;OK&quot;,
        ///	&quot;restartButton&quot;: &quot;redemarrer maintenant&quot;,
        ///	&quot;restartButton8&quot;: &quot;redemarrer maintenant&quot;,
        ///	&quot;restartButton10&quot;: &quot;redemarrer maintenant&quot;,
        ///	&quot;restartAndApply&quot;: &quot;Redemarrer pour appliquer les changements?&quot;,
        ///	&quot;txtVersion&quot;: &quot;Version: {VN}&quot;,
        ///	&quot;txtBitness&quot;: &quot;Vous travaillez avec {BITS}&quot;,
        ///	&quot;linkUpdate&quot;: &quot;Mise a jour disponible&quot;,
        ///	&quot;CleanPreviewForm&quot;: &quot;Nettoyer L&apos;aperçu&quot;,
        ///	&quot;lblLab&quot;: &quot;build Experimental\n(supprimer apres avoir teste)&quot;,
        ///	&quot;performanceSw&quot;: &quot;Activer les Tweaks de Performance&quot;,
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FR {
            get {
                return ResourceManager.GetString("FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap france {
            get {
                object obj = ResourceManager.GetObject("france", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap germany {
            get {
                object obj = ResourceManager.GetObject("germany", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off 
        ///pushd &quot;%~dp0&quot; 
        ///dir /b %SystemRoot%\servicing\Packages\Microsoft-Windows-GroupPolicy-ClientExtensions-Package~3*.mum &gt;List.txt 
        ///dir /b %SystemRoot%\servicing\Packages\Microsoft-Windows-GroupPolicy-ClientTools-Package~3*.mum &gt;&gt;List.txt 
        ///for /f %%i in (&apos;findstr /i . List.txt 2^&gt;nul&apos;) do dism /online /norestart /add-package:&quot;%SystemRoot%\servicing\Packages\%%i&quot; 
        ///.
        /// </summary>
        internal static string GPEditEnablerInHome {
            get {
                return ResourceManager.GetString("GPEditEnablerInHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap greece {
            get {
                object obj = ResourceManager.GetObject("greece", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] hosts {
            get {
                object obj = ResourceManager.GetObject("hosts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CLASSES_ROOT\*\shell\runas]
        ///@=&quot;Take Ownership&quot;
        ///&quot;NoWorkingDirectory&quot;=&quot;&quot;
        ///
        ///[HKEY_CLASSES_ROOT\*\shell\runas\command]
        ///@=&quot;cmd.exe /c takeown /f \&quot;%1\&quot; &amp;&amp; icacls \&quot;%1\&quot; /grant administrators:F&quot;
        ///&quot;IsolatedCommand&quot;=&quot;cmd.exe /c takeown /f \&quot;%1\&quot; &amp;&amp; icacls \&quot;%1\&quot; /grant administrators:F&quot;
        ///
        ///[HKEY_CLASSES_ROOT\Directory\shell\runas]
        ///@=&quot;Take Ownership&quot;
        ///&quot;NoWorkingDirectory&quot;=&quot;&quot;
        ///
        ///[HKEY_CLASSES_ROOT\Directory\shell\runas\command]
        ///@=&quot;cmd.exe /c takeown /f \&quot;%1\&quot; /r /d y &amp;&amp; icacls \&quot;% [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InstallTakeOwnership {
            get {
                return ResourceManager.GetString("InstallTakeOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;btnAbout&quot;: &quot;OK&quot;,
        ///	&quot;restartButton&quot;: &quot;riavvia ora&quot;,
        ///	&quot;restartButton8&quot;: &quot;riavvia ora&quot;,
        ///	&quot;restartButton10&quot;: &quot;riavvia ora&quot;,
        ///	&quot;restartAndApply&quot;: &quot;Riavviare per applicare le modifiche?&quot;,
        ///	&quot;txtVersion&quot;: &quot;Versione: {VN}&quot;,
        ///	&quot;txtBitness&quot;: &quot;Architettura: {BITS}&quot;,
        ///	&quot;linkUpdate&quot;: &quot;Aggiornamento disponibile&quot;,
        ///	&quot;lblLab&quot;: &quot;Build sperimentale\n(cancellare dopo il test)&quot;,
        ///	&quot;performanceSw&quot;: &quot;Abilita miglioramento prestazioni&quot;,
        ///	&quot;networkSw&quot;: &quot;Disabilita rallentamento della rete&quot;,
        ///	&quot;defenderSw&quot;: &quot;Disabilita Windows Defender&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IT {
            get {
                return ResourceManager.GetString("IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap italy {
            get {
                object obj = ResourceManager.GetObject("italy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///     &quot;btnAbout&quot;: &quot;확인&quot;,
        ///	&quot;restartButton&quot;: &quot;지금 다시 시작&quot;,
        ///	&quot;restartButton8&quot;: &quot;지금 다시 시작&quot;,
        ///	&quot;restartButton10&quot;: &quot;지금 다시 시작&quot;,
        ///	&quot;restartAndApply&quot;: &quot;변경을 적용하려면 다시 시작하시겠습니까?&quot;,
        ///	&quot;txtVersion&quot;: &quot;버전: {VN}&quot;,
        ///	&quot;txtBitness&quot;: &quot;{BITS}로 작업중입니다&quot;,
        ///	&quot;linkUpdate&quot;: &quot;업데이트 가능&quot;,
        ///	&quot;lblLab&quot;: &quot;실험 빌드\n(테스트 후 삭제)&quot;,
        ///	&quot;performanceSw&quot;: &quot;성능 조정을 활성화&quot;,
        ///	&quot;networkSw&quot;: &quot;네트워크 조절 사용 안 함&quot;,
        ///	&quot;defenderSw&quot;: &quot;Windows Defender 사용 안 함&quot;,
        ///	&quot;systemRestoreSw&quot;: &quot;시스템 복원 사용 안 함&quot;,
        ///	&quot;printSw&quot;: &quot;인쇄 서비스 사용 안 함&quot;,
        ///	&quot;mediaSharingSw&quot;: &quot;Media Player 공유 사용 안 함&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KO {
            get {
                return ResourceManager.GetString("KO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap korea {
            get {
                object obj = ResourceManager.GetObject("korea", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OneDrive_Uninstaller {
            get {
                object obj = ResourceManager.GetObject("OneDrive_Uninstaller", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;btnAbout&quot;: &quot;OK&quot;,
        ///	&quot;restartButton&quot;: &quot;Uruchom ponownie&quot;,
        ///	&quot;restartButton8&quot;: &quot;Uruchom ponownie&quot;,
        ///	&quot;restartButton10&quot;: &quot;Uruchom ponownie&quot;,
        ///	&quot;restartAndApply&quot;: &quot;Uruchomić ponownie aby zastosować zmiany?&quot;,
        ///	&quot;txtVersion&quot;: &quot;Obecna wersja: {VN}&quot;,
        ///	&quot;txtBitness&quot;: &quot;Praca na {BITS} bitach&quot;,
        ///	&quot;linkUpdate&quot;: &quot;Dostępna aktualizacja&quot;,
        ///	&quot;lblLab&quot;: &quot;Eksperymentalna kompilacja\n(usuwana po testowaniu)&quot;,
        ///	&quot;performanceSw&quot;: &quot;Włącz ulepszenia wydajności&quot;,
        ///	&quot;networkSw&quot;: &quot;Wyłącz Network Throttling&quot;,
        ///	&quot;defenderSw&quot;: &quot;Wyłą [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PL {
            get {
                return ResourceManager.GetString("PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap poland {
            get {
                object obj = ResourceManager.GetObject("poland", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CLASSES_ROOT\DesktopBackground\Shell\Power Menu]
        ///&quot;MUIVerb&quot;=&quot;Power Menu&quot;
        ///&quot;SubCommands&quot;=&quot;lock;logoff;switch;sleep;hibernate;restart;safemode;shutdown;hybridshutdown&quot;
        ///&quot;Icon&quot;=&quot;shell32.dll,215&quot;
        ///&quot;Position&quot;=&quot;bottom&quot;
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\lock]
        ///@=&quot;Lock&quot;
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\lock\command]
        ///@=&quot;Rundll32 User32.dll,LockWorkStati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PowerMenu {
            get {
                return ResourceManager.GetString("PowerMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;btnAbout&quot;: &quot;OK&quot;,
        ///	&quot;restartButton&quot;: &quot;reinicie agora&quot;,
        ///	&quot;restartButton8&quot;: &quot;reinicie agora&quot;,
        ///	&quot;restartButton10&quot;: &quot;reinicie agora&quot;,
        ///	&quot;restartAndApply&quot;: &quot;Reiniciar para aplicar as alterações?&quot;,
        ///	&quot;CleanPreviewForm&quot;: &quot;Antevisão Limpa&quot;,
        ///	&quot;txtVersion&quot;: &quot;Versão: {VN}&quot;,
        ///	&quot;txtBitness&quot;: &quot;A arquitetura do seu computador é de {BITS}.&quot;,
        ///	&quot;linkUpdate&quot;: &quot;Nova atualização disponível&quot;,
        ///	&quot;lblLab&quot;: &quot;Experimentar nova implementação\n(deletar após teste)&quot;,
        ///	&quot;performanceSw&quot;: &quot;Habilitar ajustes de desempenho&quot;,
        ///	&quot;networkSw&quot;: &quot;Des [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PT {
            get {
                return ResourceManager.GetString("PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///
        ///[-HKEY_CLASSES_ROOT\*\shell\runas]
        ///
        ///[-HKEY_CLASSES_ROOT\Directory\shell\runas]
        ///.
        /// </summary>
        internal static string RemoveTakeOwnership {
            get {
                return ResourceManager.GetString("RemoveTakeOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;btnAbout&quot;: &quot;OK&quot;,
        ///	&quot;restartButton&quot;: &quot;Перезапустить сейчас&quot;,
        ///	&quot;restartButton8&quot;: &quot;Перезапустить сейчас&quot;,
        ///	&quot;restartButton10&quot;: &quot;Перезапустить сейчас&quot;,
        ///	&quot;restartAndApply&quot;: &quot;Перезапустить, чтобы применить изменения?&quot;,
        ///	&quot;txtVersion&quot;: &quot;Версия: {VN}&quot;,
        ///	&quot;txtBitness&quot;: &quot;Вы работаете с {BITS}&quot;,
        ///	&quot;linkUpdate&quot;: &quot;Доступно новое обновление&quot;,
        ///	&quot;lblLab&quot;: &quot;Экспериментальная версия\n(удалить после тестирования)&quot;,
        ///	&quot;performanceSw&quot;: &quot;Включить настройки оптимизации&quot;,
        ///	&quot;networkSw&quot;: &quot;Отключить троттлинг сети&quot;,
        ///	&quot;defenderSw&quot;: &quot;Отк [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RU {
            get {
                return ResourceManager.GetString("RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap russia {
            get {
                object obj = ResourceManager.GetObject("russia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spain {
            get {
                object obj = ResourceManager.GetObject("spain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CLASSES_ROOT\DesktopBackground\Shell\SystemShortcuts]
        ///&quot;MUIVerb&quot;=&quot;System Shortcuts&quot;
        ///&quot;SubCommands&quot;=&quot;admintools;datetime;regional;folderoptions;gmode;internetoptions;network;power;appwiz;rbin;run;search;services;sysdm;user;user2;flip3d&quot;
        ///&quot;icon&quot;=&quot;sysdm.cpl&quot;
        ///&quot;Position&quot;=-
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\admintools]
        ///@=&quot;Administrative Tools&quot;
        ///&quot;icon&quot;=&quot;imageres.dll,109&quot;
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Micros [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SystemShortcuts {
            get {
                return ResourceManager.GetString("SystemShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CLASSES_ROOT\DesktopBackground\Shell\SystemTools]
        ///&quot;MUIVerb&quot;=&quot;System Tools&quot;
        ///&quot;SubCommands&quot;=&quot;control;cleanmgr;devmgr;event;regedit;secctr;msconfig;taskmgr;taskschd;wu&quot;
        ///&quot;icon&quot;=&quot;imageres.dll,104&quot;
        ///&quot;Position&quot;=-
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\control]
        ///@=&quot;Control Panel&quot;
        ///&quot;icon&quot;=&quot;control.exe&quot;
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\control\command]
        ///@=&quot;c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SystemTools {
            get {
                return ResourceManager.GetString("SystemTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;btnAbout&quot;: &quot;OK&quot;,
        ///	&quot;restartButton&quot;: &quot;şimdi yeniden başlat&quot;,
        ///	&quot;restartButton8&quot;: &quot;şimdi yeniden başlat&quot;,
        ///	&quot;restartButton10&quot;: &quot;şimdi yeniden başlat&quot;,
        ///	&quot;restartAndApply&quot;: &quot;Değişiklikleri uygulamak için yeniden başlatılsın mı?&quot;,
        ///	&quot;txtVersion&quot;: &quot;Versiyon: {VN}&quot;,
        ///	&quot;txtBitness&quot;: &quot;{BITS} ile çalışıyor.&quot;,
        ///	&quot;CleanPreviewForm&quot;: &quot;Temiz Önizleme&quot;,
        ///	&quot;linkUpdate&quot;: &quot;Güncelleme Mevcut&quot;,
        ///	&quot;lblLab&quot;: &quot;Deneysel Yapı\n(Testten sonra silin)&quot;,
        ///	&quot;performanceSw&quot;: &quot;Performans Ayarlarını Etkinleştir&quot;,
        ///	&quot;networkSw&quot;: &quot;Ağ Kısıtlamasını [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TR {
            get {
                return ResourceManager.GetString("TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap turkey {
            get {
                object obj = ResourceManager.GetObject("turkey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;btnAbout&quot;: &quot;確定&quot;,
        ///	&quot;restartButton&quot;: &quot;現在重啟&quot;,
        ///	&quot;restartButton8&quot;: &quot;現在重啟&quot;,
        ///	&quot;restartButton10&quot;: &quot;現在重啟&quot;,
        ///	&quot;restartAndApply&quot;: &quot;重新啟動以應用更改?&quot;,
        ///	&quot;txtVersion&quot;: &quot;版本: {VN}&quot;,
        ///	&quot;txtBitness&quot;: &quot;您使用的是{BITS}&quot;,
        ///	&quot;linkUpdate&quot;: &quot;更新可用&quot;,
        ///	&quot;lblLab&quot;: &quot;實驗構建\n(刪除後測試)&quot;,
        ///	&quot;performanceSw&quot;: &quot;啟用性能調整&quot;,
        ///	&quot;networkSw&quot;: &quot;禁用網路節流&quot;,
        ///	&quot;defenderSw&quot;: &quot;禁用 Windows Defender&quot;,
        ///	&quot;systemRestoreSw&quot;: &quot;禁用 System Restore&quot;,
        ///	&quot;printSw&quot;: &quot;禁用列印服務&quot;,
        ///	&quot;mediaSharingSw&quot;: &quot;禁用媒體播放器分享&quot;,
        ///	&quot;faxSw&quot;: &quot;禁用傳真服務&quot;,
        ///	&quot;reportingSw&quot;: &quot;禁用錯誤報告&quot;,
        ///	&quot;homegroupSw&quot;: &quot;禁用 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TW {
            get {
                return ResourceManager.GetString("TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap united_kingdom {
            get {
                object obj = ResourceManager.GetObject("united_kingdom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CLASSES_ROOT\DesktopBackground\Shell\WindowsApps]
        ///&quot;MUIVerb&quot;=&quot;Windows Apps&quot;
        ///&quot;SubCommands&quot;=&quot;calc;chmap;cmd;dfrg;ie;notepad;paint;psr;snip;srd;srt;tsch;wmp;wordpad&quot;
        ///&quot;icon&quot;=&quot;imageres.dll,152&quot;
        ///&quot;Position&quot;=-
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\calc]
        ///@=&quot;Calculator&quot;
        ///&quot;icon&quot;=&quot;calc.exe&quot;
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\calc\command]
        ///@=&quot;calc.exe&quot;
        ///
        ///[HK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WindowsApps {
            get {
                return ResourceManager.GetString("WindowsApps", resourceCulture);
            }
        }
    }
}
